name= "AFL - Selkie Medical Mod 0.0.0";
picture = "logo.paa";
logo= "logo.paa";
logoOver= "logo.paa";
action= "https://flufflesamy.github.io/AFL/";
description= "AFL - Selkie Medical Mod 0.0.0"
tooltip = "AFL";
tooltipOwned = "AFL Owned";
overviewPicture = "logo.paa";
overview = "AFL- Selkie Medical Mod contains various helpful components, including a medical simulator, a vehicle spawner, and a mission that integrates both. This mod is intended to be used in the Selkie platoon.";
