[sqf.var_all_caps]
options.ignore = [
    "AFL_*"
]

[sqf.banned_macros]
options.release = [
    "DEBUG_MODE_FULL",
    "DISABLE_COMPILE_CACHE",
    "ENABLE_PERFORMANCE_COUNTERS"
]

[sqf.command_case]
options.ignore = [
    "*"
]

[stringtables.usage]
options.ignore_unused = true
options.ignore_missing = false
options.ignore_duplicate = false
