name = "AFL - Selkie Medical Mod"
author = "flufflesamy"
prefix = "AFL"
mainprefix = "z"

[files]
include = [
    "LICENSE",
    "README.md",
    "logo.paa",
    "CHANGELOG.md",
    "meta.cpp",
    "AUTHORS.txt"
]

[version]
git_hash = 0

[rapify]
exclude = [
    "*.ext"
]
