name = "Amy Functions Library for Arma 3"
author = "flufflesamy"
prefix = "AFL"
mainprefix = "z"

[files]
include = [
    "LICENSE",
    "README.md",
    "logo.paa",
    "CHANGELOG.md"
]

[version]
git_hash = 0
