name: Docs
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-docs:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup mdBook
        uses: taiki-e/install-action@mdbook

      - name: Setup mdBook-admonish
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-admonish

      - name: Setup mdbook-image-size
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-image-size

      - name: Setup mdbook-inline-highlighting
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-inline-highlighting

      - name: Setup mdbook-toc
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-toc

      - name: Build Book
        run: |
          cd docs
          mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
